# Generated by Django 5.2.17 on 2026-09-16 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='changed_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='environment',
            field=models.CharField(default='development', max_length=40),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='error_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='error_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='level',
            field=models.CharField(default='INFO', max_length=16),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='module',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='portal_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='service',
            field=models.CharField(default='startup-api', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='stack_trace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='trace_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
