# Generated by Django 5.2.17 on 2026-09-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activitylog_action_activitylog_changed_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('view', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(default='bi-circle', max_length=80)),
                ('required_permission', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.menuitem')),
            ],
            options={
                'ordering': ('parent_id', 'sort_order', 'id'),
            },
        ),
    ]
