# Generated by Django 5.2.17 on 2026-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
