# Generated by Django 5.2.17 on 2026-09-18 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('article_type', models.CharField(default='article', max_length=64)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Deleted'), (1, 'Approved'), (2, 'Pending')], default=2)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('ordering', models.IntegerField(default=0)),
                ('show_home', models.BooleanField(default=False)),
                ('is_feature', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('public_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-public_date', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category_type', models.CharField(default='article', max_length=64)),
                ('status', models.SmallIntegerField(default=1)),
                ('ordering', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ArticleCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('language_code', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url_key', models.CharField(blank=True, max_length=255)),
                ('status', models.SmallIntegerField(default=1)),
                ('meta_keyword', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('language_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('raw_title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Deleted'), (1, 'Approved'), (2, 'Pending')], default=2)),
                ('public_date', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('url_key', models.CharField(max_length=255)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_name', models.CharField(blank=True, max_length=255)),
                ('seo_content', models.TextField(blank=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='mediafile',
            new_name='api_mediafi_created_366f24_idx',
            old_name='api_mediafi_created_4c1b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='mediafile',
            new_name='api_mediafi_origina_3aeb29_idx',
            old_name='api_mediafi_origina_9d66e4_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='api.mediafile'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.articlecategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='api.articlecategory'),
        ),
        migrations.AddField(
            model_name='articlecategorytranslation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.articlecategory'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.article'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_translation_images', to='api.mediafile'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-public_date'], name='api_article_status_45296b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_type', 'status'], name='api_article_article_b2c043_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlecategorytranslation',
            constraint=models.UniqueConstraint(fields=('category', 'language_code'), name='unique_article_category_language'),
        ),
        migrations.AddIndex(
            model_name='articletranslation',
            index=models.Index(fields=['language_code', 'status'], name='api_article_languag_f9d9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='articletranslation',
            index=models.Index(fields=['url_key', 'language_code'], name='api_article_url_key_f3d74d_idx'),
        ),
        migrations.AddConstraint(
            model_name='articletranslation',
            constraint=models.UniqueConstraint(fields=('article', 'language_code'), name='unique_article_language'),
        ),
    ]
