# Generated by Django 5.2.17 on 2026-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_article_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='legacy_author_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='legacy_image_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='legacy_author_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='legacy_feature_image_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='raw_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='raw_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
