# Generated by Django 5.2.17 on 2026-09-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_split_products_menu'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_kind_15170f_idx',
            old_name='api_product_kind_6d1e6a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_categor_ff2e3e_idx',
            old_name='api_product_categ_1c0b24_idx',
        ),
        migrations.RenameIndex(
            model_name='producttranslation',
            new_name='api_product_languag_938ac2_idx',
            old_name='api_productt_langua_0f1a4d_idx',
        ),
        migrations.RenameIndex(
            model_name='producttranslation',
            new_name='api_product_url_key_276655_idx',
            old_name='api_productt_url_key_9f6c77_idx',
        ),
    ]
