# Generated by Django 5.2.17 on 2026-09-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_seed_service_promotion_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('ordering', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('ordering', 'name', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(default='service', max_length=30),
        ),
    ]
