# Generated by Django 5.2.17 on 2026-09-23 09:58

from django.db import migrations, models


def migrate_recruitment_tags(apps, schema_editor):
    RecruitmentTag = apps.get_model("api", "RecruitmentTag")
    ProductTag = apps.get_model("api", "ProductTag")
    for tag in RecruitmentTag.objects.all():
        ProductTag.objects.get_or_create(name=tag.name[:80], defaults={"slug": tag.slug[:100]})


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_recruitmentdepartment_recruitmenttag_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_recruitment_tags, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="RecruitmentTag",
        ),
        migrations.AlterField(
            model_name="recruitmentjob",
            name="managed_tags",
            field=models.ManyToManyField(
                blank=True, related_name="recruitment_jobs", to="api.producttag"
            ),
        ),
    ]
