# Generated by Django 5.2 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0064_unlock_page_template_regions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("short_code", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("fields", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("name", "id")},
        ),
    ]