from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    MenuDetailView,
    MenuListCreateView,
    MenuGroupListCreateView,
    MenuGroupDetailView,
    MeView,
    UserProfileView,
    UserAvatarView,
    ChangePasswordView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    RegisterView,
    RoleListCreateView,
    SessionListView,
    SessionRevokeView,
    UserRoleView,
    UserAdminListCreateView,
    UserAdminDetailView,
    PermissionListView,
    RoleDetailView,
)
from ..settings.views import EmailConfigurationView, EmailTestView

urlpatterns = [
    path("menus/", MenuGroupListCreateView.as_view(), name="auth-menus"),
    path("menus/<int:menu_id>/", MenuGroupDetailView.as_view(), name="auth-menu-group-detail"),
    path("register/", RegisterView.as_view(), name="auth-register"),
    path("login/", LoginView.as_view(), name="auth-login"),
    path("logout/", LogoutView.as_view(), name="auth-logout"),
    path("me/", MeView.as_view(), name="auth-me"),
    path("profile/", UserProfileView.as_view(), name="auth-profile"),
    path("profile/avatar/", UserAvatarView.as_view(), name="auth-profile-avatar-upload"),
    path("profile/<int:user_id>/avatar/", UserAvatarView.as_view(), name="auth-profile-avatar"),
    path("password/change/", ChangePasswordView.as_view(), name="auth-password-change"),
    path("password/reset/request/", PasswordResetRequestView.as_view(), name="auth-password-reset-request"),
    path("password/reset/confirm/", PasswordResetConfirmView.as_view(), name="auth-password-reset-confirm"),
    path("sessions/", SessionListView.as_view(), name="auth-sessions"),
    path("sessions/<uuid:session_id>/revoke/", SessionRevokeView.as_view(), name="auth-session-revoke"),
    path("roles/", RoleListCreateView.as_view(), name="auth-roles"),
    path("roles/<int:role_id>/", RoleDetailView.as_view(), name="auth-role-detail"),
    path("permissions/", PermissionListView.as_view(), name="auth-permissions"),
    path("menu/", MenuListCreateView.as_view(), name="auth-menu"),
    path("menu/<int:menu_id>/", MenuDetailView.as_view(), name="auth-menu-detail"),
    path("users/<int:user_id>/roles/", UserRoleView.as_view(), name="auth-user-roles"),
    path("users/", UserAdminListCreateView.as_view(), name="auth-users"),
    path("users/<int:user_id>/", UserAdminDetailView.as_view(), name="auth-user-detail"),
    path("settings/email/", EmailConfigurationView.as_view(), name="auth-email-configuration-legacy"),
    path("settings/email/test/", EmailTestView.as_view(), name="auth-email-test-legacy"),
]
